version: '3'
services:
  rails:
    build: .
    image: 'rails'
    command: [
      'prehook', 'rm -f /app/tmp/pids/server.pid', '--',
      'prehook', 'bundle install --jobs 4', '--',
      'codep',
        'bundle exec rails s -p 3000 -b 0.0.0.0',
        'bin/webpack-dev-server'
    ]
    volumes:
      - .:/app
      - bundle_install:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
volumes:
  bundle_install:
    driver: local
  node_modules:
    driver: local